### ISSUE TITLE
BUG: argument to path.resolve must be a string.

### ISSUE THREAD

**Issue by trusktr** [Sanjo/meteor-meteor-files-helpers#5]
I'm getting this on line https://github.com/Sanjo/meteor-meteor-files-helpers/blob/master/src/meteor_files_helpers.js#L12:

```
 ❯ meteor publish                                                                                                    [17:47:22]
rocket:module: updating npm dependencies -- rndm, lodash, glob, user-home, semver...
 ------------------- IS APP BUILD -----------------
 false
=> Errors while initializing project:

While loading plugin `rocket:module` from package `rocket:module`:
path.js:313:15: Arguments to path.resolve must be strings
at Object.exports.resolve (path.js:313:15)
at Object.MeteorFilesHelpers.getAppPath (packages/sanjo:meteor-files-helpers/meteor_files_helpers.js:12:1)
at appDir (packages/rocket:module/plugin/plugin.js:31:1)
at Package (packages/rocket:module/plugin/plugin.js:552:1)
at <runJavaScript-37>:597:4
at <runJavaScript-37>:604:3
```

Looking into it.

**Comment by trusktr** [comment]
It's happening during publish, but not during app builds. hmmm...

**Comment by trusktr** [comment]
Found it. It's because `findAppDir` can return `null` and `path.resolve` can't take `null`.
