### ISSUE TITLE
Arguments to path.join must be strings

### ISSUE THREAD

**Issue by cwaring** [Sanjo/meteor-meteor-files-helpers#9]
Hi Jonas. I'm currently having issues depending on your file helpers in Meteor 1.2. While attempting to publish a new version of my package the `meteor lint` tool fails with the following error.

```js
While loading plugin `cssnext-basscss` from package `kit:cssnext-basscss`:
path.js:360:15: Arguments to path.join must be strings
at path.js:360:15
at Array.filter (native)
at Object.exports.join (path.js:358:36)
at Object.MeteorFilesHelpers.getNodeModulePath (packages/sanjo_meteor-files-helpers/meteor_files_helpers.js:48:1)
at Package (plugin/compile.js:5:22)
at <runJavaScript-43>:66:4
at <runJavaScript-43>:73:3
```

It works at runtime within my local app but I guess the linter could be running outside of an application context and [`getAppPath()`](https://github.com/Sanjo/meteor-meteor-files-helpers/blob/master/src/meteor_files_helpers.js#L11-L13) fails by returning `null` (which path rejects).

What is the best way to fix this? I'm looking for a reliable way to resolve the path to an included node module.

Call `kit:cssnext-basscss` that is [causing the failure](https://github.com/cwaring/meteor-cssnext-basscss/blob/master/plugin/compile.js#L3-L8)

**Comment by Sanjo** [comment]
The app directory is found via `process.cwd()`, so you could console.log it before the error happens to see what it is. Then we can see how we can fix it.

**Comment by cwaring** [comment]
`meteor publish` / `meteor lint` fails when running from my shared `$PACKAGE_DIRS` `/Users/cw/wwaves/meteor-packages` folder.

`process.cwd()` = `/Users/cw/wwaves/meteor-packages/kit:cssnext-basscss`

**Comment by cwaring** [comment]
I've managed to publish a new version of my package by tricking the build tool into using a [static path](https://github.com/cwaring/meteor-cssnext-basscss/blob/master/plugin/compile.js#L10-L17) when getNodeModulePath() fails.

I guess process.cwd() has changed when publishing packages with 1.2. There's probably a better way to fix this but it works for now :)

Thanks for your work on this package btw, really helps get over Meteor's shortcoming for handling file paths.

**Comment by Sanjo** [comment]
Ok. I think I can handle your case in getNodeModulePath.

**Comment by cwaring** [comment]
Great, really appreciate that. Let me know when you have something to test. :+1:
